FROM node:lts-buster
WORKDIR /work

ENV JAACKD_REALITY_GITHUB_OAUTH_CLIENT_ID="$JAACKD_REALITY_GITHUB_OAUTH_CLIENT_ID"
ENV JAACKD_REALITY_GITHUB_OAUTH_CLIENT_SECRET="$JAACKD_REALITY_GITHUB_OAUTH_CLIENT_SECRET"
ENV NDTECH_NODE_API_SERVER_NAME="$NDTECH_NODE_API_SERVER_NAME"
ENV NDTECH_NODE_API_SERVER_PORT=$NDTECH_NODE_API_SERVER_PORT   
ENV NDTECH_NODE_API_IS_HTTPS="$NDTECH_NODE_API_IS_HTTPS"
ENV NDTECH_NODE_API_DB_SERVER="$NDTECH_NODE_API_DB_SERVER"
ENV NDTECH_NODE_API_DB_NAME="$NDTECH_NODE_API_DB_NAME"
ENV NDTECH_NODE_API_DB_USER="$NDTECH_NODE_API_DB_USER" 
ENV NDTECH_NODE_API_DB_PASSWORD="$NDTECH_NODE_API_DB_PASSWORD"

COPY ./package.json ./
RUN npm install

COPY . .

ENTRYPOINT [ "npm", "run", "start" ]