apiVersion: v1
kind: ConfigMap
metadata:
  name: ndtech-node-api
  namespace: ndtech
data:
  JAACKD_REALITY_GITHUB_OAUTH_CLIENT_ID: "2d4079dfff80ceb2c3a7"
  NDTECH_NODE_API_SERVER_NAME: "localhost"
  NDTECH_NODE_API_SERVER_PORT: "5000"
  NDTECH_NODE_API_IS_HTTPS: "false"
  NDTECH_NODE_API_DB_SERVER: "mongodb-0.mongodb-svc.mongo.svc.cluster.local:27017,mongodb-1.mongodb-svc.mongo.svc.cluster.local:27017,mongodb-2.mongodb-svc.mongo.svc.cluster.local"
  NDTECH_NODE_API_DB_NAME: "ndtech-sapper"
  NDTECH_NODE_API_DB_USER: "ndtech-sapper"