---
apiVersion: v1
kind: Service
metadata:
  name: ndtech-node-api
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    app: ndtech-node-api
  ports:
    - port: 80
      targetPort: 5000